### ISSUE TITLE
Please fix the Windows installer!

### ISSUE THREAD

**Issue by YetAnotherSiteThatNeedsMyInfo** [C0untFloyd/bark-gui#107]
The Windows Installer does not work!
ERROR: Cannot install -r requirements.txt (line 2) and fairseq because these package versions have conflicting dependencies.

The conflict is caused by:
    fairseq 0.12.4 depends on omegaconf<2.1
    hydra-core 1.0.7 depends on omegaconf<2.1 and >=2.0.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Traceback (most recent call last):
  File "D:\Other\bark-gui-main\bark-gui-main\installer\bark-gui\webui.py", line 5, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

Done!
Press any key to continue . . .

Followed by:

Traceback (most recent call last):
  File "D:\Other\bark-gui-main\bark-gui-main\installer\bark-gui\webui.py", line 5, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

Done!
Press any key to continue . . .

**Comment by YetAnotherSiteThatNeedsMyInfo** [comment]
To those also having this problem, it is becoming increasingly clear that this repo has been abandoned as the installer did not work months ago when I tried initially and yet no changes have been made since then, no response from developer.

**Comment by helpmebro911** [comment]
pls fix

**Comment by HiyungXu** [comment]
downgrade pip to 24.0

**Comment by YetAnotherSiteThatNeedsMyInfo** [comment]
> downgrade pip to 24.0 
>
This worked!
As well as downgrading Gradio which is already a known fix.
