### ISSUE TITLE
Prompt steps say something less

### ISSUE THREAD

**Issue by wyl2000** [C0untFloyd/bark-gui#13]
It is best to create a folder with an AI or other name on the SSD hard disk, enter this folder under window11, enter cmd or Powershell in the address bar, and enter in the black command line
git clone https://github.com/C0untFloyd/bark-gui
You will download a bark-gui folder to the AI folder you created,
At this time, you need to enter bark-gui from the command line or enter cmd in the address bar again under the bark-gui folder in windows, and then execute
pip install .
Otherwise, it will prompt that the .py file cannot be found.
pip install gradio
pip install soundfile
If you have installed stablediffusion, you may have a window environment, pytorch2.0, do not run windows_start.bat directly, you will download and install all of them once, this script is not smart enough, and it is not very good for novices. The author's hints are not easy for me as a novice to understand, and I wasted a lot of time. No conversational scripts are installed. I hope these mistakes will help others.

**Comment by C0untFloyd** [comment]
I'm sorry for your problems, your instructions were kind of hard to understand though. You could try the new bugfixed 1-click-installer, I do believe it is working a lot better now and will install in a secured conda environment.
