### ISSUE TITLE
Improvement request: Network service accessibility

### ISSUE THREAD

**Issue by ghadeb** [C0untFloyd/bark-gui#16]
Hi, amazing work you're doing with your development, really appreciate your contribution for the opensource and AI communities.

I love the idea of having the UI to access Bark's features, but it would be awesome if you could add some network availability through some flags like adding --listen and --port, just as we seen in a couple other frontends.

Food for thought :)

Thanks for all the work and commitment!

**Comment by C0untFloyd** [comment]
Thanks and check out the latest version which has a configuration screen which - among other stuff - allows you to create a public server and specify a the server port 😃

**Comment by ghadeb** [comment]
Oh, that's great!!! Thanks!

**Comment by SuperUserNameMan** [comment]
How do you do that from command line for when your Ui is running on an other computer from SSH ?

edit : never mind, i just edited `config.yaml` and set server name to 0.0.0.0
