### ISSUE TITLE
API Mode

### ISSUE THREAD

**Issue by JamesLaFritz** [C0untFloyd/bark-gui#18]
This works great. I couldn't get the original to work on my machine, Yours worked perfectly. Can I use it in API Mode? Like [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui)? Feed it the text string from another app, and get the voice back?

**Comment by C0untFloyd** [comment]
Yes, this should be possible by using the inbuilt REST-API (although I didn't add specific code or tried it myself so far). Another guy asked something similar already here: #5

**Comment by JamesLaFritz** [comment]
Thanks I missed #5 I'll look at the article there and see if I can get it working the way that I want thanks.
