### ISSUE TITLE
readme.md encoding causing install to crash.

### ISSUE THREAD

**Issue by antrys** [C0untFloyd/bark-gui#2]
I had to load up the README.md into vs code and save it as utf-8 to get the 'pip install .' installer to run.

**Comment by C0untFloyd** [comment]
@antrys Thanks for the heads up! This should be fixed by the latest commit.

@adso3210 Try reinstalling torch and dependencies like this: `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 --force-reinstall`

**Comment by adso3210** [comment]
that fixed it. Thank you!

**Comment by derklinge** [comment]
Can confirm. Fixed it for me, too.
