### ISSUE TITLE
Unable to enablemps 

### ISSUE THREAD

**Issue by leejr72** [C0untFloyd/bark-gui#20]
Thank you for putting this together.

Testing on a MAC M2 and was not able to enablemps

Also needed to do a pip install cchardet

![image](https://github.com/C0untFloyd/bark-gui/assets/110568703/4c00a047-bad9-4154-9519-f5cad38a1b52)

![image](https://github.com/C0untFloyd/bark-gui/assets/110568703/94fa3b9a-2ade-4ff6-85bd-fa05ce393251)

let me know if not trying correctly

**Comment by C0untFloyd** [comment]
I'm sorry this really was a bug, fixed in the latest update v0.4.7 today, please update.
Bark is not using cchardet AFAIK but perhaps this is needed for Gradio on Mac 🤷
