### ISSUE TITLE
Stuck at downloading model

### ISSUE THREAD

**Issue by WaGi-Coding** [C0untFloyd/bark-gui#25]
I am stuck at

_Preloading Models
Downloading text suno/bark remote model file https://huggingface.co/suno/bark/resolve/main/text_2.pt text_2.pt to ./models_

I have like 500MBit/s max Download speed, but this never finishes or shows any status.

I am on Windows 10 using the latest release 1 click installer

Any help would be appreciated

**Comment by Magenta-6** [comment]
@WaGi-Coding 
Same happened to me. 
I downloaded it separately along with the other models. 
Bunged them in the models folder.
Closed the installer and then restarted it.
It found the models and worked perfectly.
Regards
@Magenta-6

**Comment by Magenta-6** [comment]
Try https://huggingface.co/suno/bark/tree/main
