### ISSUE TITLE
[Suggestion] Support for .srt

### ISSUE THREAD

**Issue by Dragoy** [C0untFloyd/bark-gui#26]
**Support for .srt**
It would be cool to have support for .srt format as text, which would be voiced depending on the timings.

**Comment by Dragoy** [comment]
Or have support for the `prosody` tag in SSML:
`<?xml version="1.0"?>
    <speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.w3.org/2001/10/synthesis
                       http://www.w3.org/TR/speech-synthesis/synthesis.xsd"
             xml:lang="en-US">
    <voice name="/v2/en_speaker_9">
	<prosody duration="21000ms">Hello, I'm Usung Kang. Welcome to the CINEMA 4D Master Class on Achieving Mastery by Gurum Kim and Taehoon Pak.</prosody>
	<prosody duration="13000ms">First of all, I'm here to say hello on behalf of both of you, and I'm very happy and excited to meet you, even though it's online.</prosody>
	<prosody duration="15000ms">We've done some basic courses through ColloSo in the past, and we're very excited to put this new course together and meet you again.</prosody>
	<prosody duration="8000ms">In this first hour, we divided the OT time into five parts.</prosody>
	<prosody duration="14000ms">In introduction of the three instructors, introduction of the work involved, key points of the class and introduction to the curriculum At the end of the OT the sun will set and the three instructors will go through all five parts.</prosody>
	</voice>
    </speak>`

**Comment by Dragoy** [comment]
This tool is ideal for converting .srt to ssml format:
https://github.com/ThioJoe/SRT-To-SSML

**Comment by Dragoy** [comment]
Now, unfortunately, this format does not work and causes an error:
<img width="852" alt="image" src="https://github.com/C0untFloyd/bark-gui/assets/4968313/91a6db09-47d8-4c88-9c66-6176e669ad95">

**Comment by C0untFloyd** [comment]
Yes, I will continue working on this format, however Bark is not the best for exact tts, as every result can be quite different and speech breaks are more or less random. Do you know if one could add custom metadata (like Seedvalue) to the SRT-STandard?
