### ISSUE TITLE
Requirements missing funcy

### ISSUE THREAD

**Issue by SoftologyPro** [C0untFloyd/bark-gui#29]
Latest install and StartBark.bat.
Complains about missing funcy on startup.
`pip install funcy` gets it working again.

**Comment by C0untFloyd** [comment]
Thanks, I don't remember installing this but I've included it (and linkify) in the requirements. Better safe than sorry.

**Comment by SoftologyPro** [comment]
Thanks for the quick response and fix.  Installs and runs fine now.
