### ISSUE TITLE
How to train the voice

### ISSUE THREAD

**Issue by KevinWang676** [C0untFloyd/bark-gui#30]
Hi, it's indeed a huge improvement. But I wonder how to train the custom voice. I clicked "Generate" and it gave an error. Do I need to upload the dataset myself? Thanks!

![image](https://github.com/C0untFloyd/bark-gui/assets/126712357/2c86f02e-0945-4951-9c4f-1c3a8d3b423a)

**Comment by C0untFloyd** [comment]
This is currently very much a work in progress, still early and really not that simple. You're not training a voice but instead training a language (how to pronounce written words). I did this by a lot of trial and error for the german language (which is downloaded if you want to clone a german speaker). I started by reading here:
[https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer](https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer)
There's a short section on how to train and a link to his data script. 
I'm short on time so briefly:

- Acquire standard literature (books) for your language as text files in UTF-8 Format
- After that semantics and WAV pairs will be generated to prepare for the real training
- Then these text/audio pairs can be used to train the 'real' model which is then used to generate the correct pronounciation for your language

I just started a wiki-page and hopefully I'll find some time to explain this better and detailed real soon.

**Comment by KevinWang676** [comment]
Thanks for your clarification and your commitment to this repo! It would be very helpful if you can further explain the training process in the future. I also have a another question. I wonder if the new voice cloning function an improved version than before. I saw you updated `[clonevoice.py](https://github.com/C0untFloyd/bark-gui/blob/main/cloning/clonevoice.py)`.

By the way, there is a small glitch. Under the ./models/hubert folder one has `en_tokenizer.pth` instead of `tokenizer.pth`.

![image](https://github.com/C0untFloyd/bark-gui/assets/126712357/b01af208-bc1f-4489-a02c-e11076ca9c71)

**Comment by C0untFloyd** [comment]
> I also have a another question. I wonder if the new voice cloning function an improved version than before because I saw you've updated [clonevoice.py](https://github.com/C0untFloyd/bark-gui/blob/main/cloning/clonevoice.py).

Yes, there were huge & important changes! The newly cloned voices finally sound a lot better and you don't need to transcribe the spoken text anymore. The drawback however is that you need the correct language model for your cloned voice.

> By the way, there is a small glitch. Under the `./models/hubert` folder one has `en_tokenizer.pth` instead of `tokenizer.pth`.

Yes, thank you for being my best beta-tester, this indeed was a bug 😄 
The latest version should download and use the specified language-model correctly. So far there are german, english and polish models available.
