### ISSUE TITLE
clonevoice can not find tokenizer.pth

### ISSUE THREAD

**Issue by hazy217** [C0untFloyd/bark-gui#31]
![image](https://github.com/C0untFloyd/bark-gui/assets/132985915/c617fcf7-957e-4cdf-b8f5-a28c7f625c8f)
clonevoice raise this error，but in the directory I find en_tokenizer.pth， Is this a mistake？
![image](https://github.com/C0untFloyd/bark-gui/assets/132985915/6036843d-0177-4296-8958-0ed1c1eed90b)

**Comment by C0untFloyd** [comment]
Yes this was a bug which I fixed in the latest release. If you don't want to upgrade right now and just want to clone english voices you can just rename en_tokenizer.pth to tokenizer.pth and it should work.
