### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_seed'

### ISSUE THREAD

**Issue by FollowDaRabbit** [C0untFloyd/bark-gui#33]
Hi I'm a newbie here.

Followed all the steps but still getting this, anyone knows what's going on? Tried google but can't even find anything related to 'pytorch_seed'.

Traceback (most recent call last):
  File "webui.py", line 11, in <module>
    import pytorch_seed
ModuleNotFoundError: No module named 'pytorch_seed'

Please help, thanks!

**Comment by C0untFloyd** [comment]
Did you use the windows installer or did you install manually? This is just one of the packages which should be installed automatically. After the error above, please type into the shell `pip install pytorch_seed`or if you have the latest version `pip install -r requirements.txt` and try starting again

**Comment by FollowDaRabbit** [comment]
Thanks @C0untFloyd!  However now encountered the following after the issue above is resolved (forgot to mention I'm running StartBark.bat on Windows 10),

Traceback (most recent call last):
  File "webui.py", line 21, in <module>
    from cloning.clonevoice import clone_voice
  File "C:\Users\J\bark-gui-main\cloning\clonevoice.py", line 4, in <module>
    from bark.hubert.pre_kmeans_hubert import CustomHubert
  File "C:\Users\J\bark-gui-main\bark\hubert\pre_kmeans_hubert.py", line 14, in <module>
    from einops import pack, unpack
ImportError: cannot import name 'pack' from 'einops' (C:\Users\J\AppData\Local\Programs\Python\Python38\lib\site-packages\einops\__init__.py)

Or should I open a new issue instead of here? Sorry it's my 1st day on GitHub. Thanks!
