### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio'

### ISSUE THREAD

**Issue by anacondabitch** [C0untFloyd/bark-gui#35]
install was successful all modules are installed D:\bark_win\installer_files\env\Lib\site-packages including gradio but when i clicked on StartBark i got this error

 DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.command.check import check
Traceback (most recent call last):
  File "D:\bark_win\bark-gui\webui.py", line 5, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

**Comment by C0untFloyd** [comment]
Please use the `windows_run.bat` when using the 1-click Windows installer NOT the StartBark.bat. I need to document this better in the readme, I'm sorry.

**Comment by 0m3ga4** [comment]
I have this issue even while running windows_run.bat
