### ISSUE TITLE
Chinese audio for less than 15 seconds

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [C0untFloyd/bark-gui#36]
I used a Chinese speech model to generate audio, and the generated audio can never exceed 15 seconds. How can I solve this problem?

**Comment by HaSaKiYasuooo** [comment]
> 你能告诉我模型生成的音频质量如何吗

Bark good at English but terrible at other languages

**Comment by HaSaKiYasuooo** [comment]
> With chinese model you probably mean a chinese speaker and for generation you used `Swap Voice`? Otherwise there is no 15s limitation in this fork?!?

So how do I solve the loss of text in the audio when Chinese is generating speech

**Comment by C0untFloyd** [comment]
Are you sure you're using this fork? As I wrote previously I don't have a audio limit.

> Bark good at English but terrible at other languages

I disagree, you just have to find a good speaker voice. At least for the languages I know, it might be different for chinese 😏

**Comment by HaSaKiYasuooo** [comment]
I tried many times to use Chinese for audio output, but the results are not satisfactory, Could you please give me some solutions

**Comment by C0untFloyd** [comment]
Is it this problem?
[https://github.com/suno-ai/bark/issues/324](https://github.com/suno-ai/bark/issues/324)
