### ISSUE TITLE
No module named Fairseq

### ISSUE THREAD

**Issue by Magenta-6** [C0untFloyd/bark-gui#38]
This is not an error from your installer, but probably a glitch at my end.

As noted previously the installer works great and opens the gui which is really nice to use.
However when I later try to run the gui using StartBark.bat I get an error:

File "C:\Users\ABC\Bark-tts\bark_win\bark-gui\bark\hubert\pre_kmeans_hubert.py", line 16, in <module>
    import fairseq
ModuleNotFoundError: No module named 'fairseq'

I know the module is in there somewhere, because it comes up on the install, however
I don't know how to get the gui activation to find the module.

At present I activate the gui by simply reinstalling it again using windows_run.bat 
which works fine, but seems un-necessary.
Putting this out there in case others have a similar issue.

Any suggestions would be appreciated - and thanks in advance.

**Comment by C0untFloyd** [comment]
You're not starting with StartBark.bat are you? windows_run.bat is both, installer and also runs the app.
Nevertheless if you encounter that error again you could try typing `pip install fairseq@https://github.com/Sharrnah/fairseq/releases/download/v0.12.4/fairseq-0.12.4-cp310-cp310-win_amd64.whl` into the shell window.

**Comment by Magenta-6** [comment]
@C0untFloyd Thanks for your advice.
Awesome!

**Comment by AIhasArrived** [comment]
Is this problem related to this issue?
https://github.com/C0untFloyd/bark-gui/issues/83
