### ISSUE TITLE
Special tags not working

### ISSUE THREAD

**Issue by FollowDaRabbit** [C0untFloyd/bark-gui#39]
No special tags are working if prompts are directly inputted, not even singing. Only read out the content without special tags. XML format is better, still only some worked. 

Anyone encountering the same thing and knows how this can be solved? Thx.

**Comment by C0untFloyd** [comment]
In my experience to get the special tags working is just pure luck or you need to experiment with different speakers. Also multiple meta tags seem to make the output a lot more unstable.

**Comment by FollowDaRabbit** [comment]
In that case we can only wait for this to be resolved in later releases and close this issue?

**Comment by FollowDaRabbit** [comment]
Thank you so much for your efforts on this repo! Really appreciated!
