### ISSUE TITLE
Can we get a full huggingface package as a 7z, post install?

### ISSUE THREAD

**Issue by kalomaze** [C0untFloyd/bark-gui#46]
<img width="1280" alt="image" src="https://github.com/C0untFloyd/bark-gui/assets/66376113/3b888ddc-ced7-438a-a5c5-a2c18c2ab5d0">
Living in a place with rural internet means that having to batch script install things has an extremely high probability of just breaking due to speed randomly :(

**Comment by C0untFloyd** [comment]
The models can be downloaded from [https://huggingface.co/suno/bark/tree/main](https://huggingface.co/suno/bark/tree/main). Just use a download manager and put them into the models directory.
For cloning/swapping voice you also need the Hubert Model from [https://dl.fbaipublicfiles.com/hubert/hubert_base_ls960.pt](https://dl.fbaipublicfiles.com/hubert/hubert_base_ls960.pt). This goes into the models/hubert folder. Hope this helps...
