### ISSUE TITLE
Using Curl possibility?

### ISSUE THREAD

**Issue by servingbaby** [C0untFloyd/bark-gui#5]
I really am liking what you have here!

I was wondering if there is a way we might be able to use CURL after launching the webgui.py to also simulate a REST type call?
(I'm a super n00b haha)

Just playing around I got something like this:

```
$ curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: 127.0.0.1" -H "Origin: http://127.0.0.1:7860" -H "Sec-WebSocket-Key: 4lgr09kc4AzoVnxzSr64UA==" -H "Sec-WebSocket-Version: 13" http://127.0.0.1:7860/queue/join 

HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: 0qVPWFBZ4HMS+aOLQhY0EgTvl+0=
date: Sun, 30 Apr 2023 17:10:00 GMT
server: uvicorn

�{"msg": "send_hash"}��
```

 But really I am trying to accomplish something like to get the payload response:
 
 curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: 127.0.0.1" -H "Origin: http://127.0.0.1:7860" -H "Sec-WebSocket-Key: 4lgr09kc4AzoVnxzSr64UA==" -H "Sec-WebSocket-Version: 13" http://127.0.0.1:7860/queue/join  -s -X POST -H "Content-Type: application/json" -d "{\"prompt\":\"Hello World!"}" http://127.0.0.1:7860
 
 In any case, having a lot of fun with this. Super new stuff I am sure will mature quickly! :)

**Comment by C0untFloyd** [comment]
Hey thanks!
The Gradio Server supports a REST API you can call, if that's what you want. Just click on the "Use via API" Link at the Bottom of the page
![API](https://user-images.githubusercontent.com/131583554/235373933-d17abbc8-1d0c-48d9-a6ed-d0c79f98f508.png)

and you'll be getting an API Description of the usable methods. This is for a python client but you should be able to use it from other means as well I guess. A quick google search did find this:
[https://www.tomsoderlund.com/ai/building-ai-powered-rest-api](https://www.tomsoderlund.com/ai/building-ai-powered-rest-api)

**Comment by servingbaby** [comment]
This had helped me spawn some interesting ideas to try, and I think I landed on something that appears to do what I was looking for. Thanxs again!
