### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by Jueun-Park** [C0untFloyd/bark-gui#52]
I am suggesting adding a refresh button for reloading prompt files.
Please take a look at this suggestion and leave comments if you have any suggestions.

### Backgrounds
I wanted to load a custom prompt file made from the 'clone voice' tab and create a custom voice, but just after generating the clone voice prompt file, I could not find the file in the TTS tab.
So the refresh button would enhance the user experience.

### Details
The stable-diffusion-webui provides the refresh button like below codes
- https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/394ffa7b0a7fff3ec484bcd084e673a8b301ccc8/modules/ui_common.py#L224

and it might be added in this part
https://github.com/C0untFloyd/bark-gui/blob/3ac2500134bd361f2401c665cf53321bd66d34f0/webui.py#L340-L342
by making a function of this part
https://github.com/C0untFloyd/bark-gui/blob/3ac2500134bd361f2401c665cf53321bd66d34f0/webui.py#L282-L292

**Comment by C0untFloyd** [comment]
I would accept a PR if this is really working. You can already sort of refresh everything by just using "Restart server" on the settings page.
