### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:

### ISSUE THREAD

**Issue by keithcarmona** [C0untFloyd/bark-gui#58]
I am on OS X Ventura and i am receiving this error message:  

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

I am running bark-gui using miniconda in its own env.   Any help would be appreciated.

**Comment by C0untFloyd** [comment]
OS X seems to dislike downloading the model weights. Try downloading them manually and put them into the models folder.
