### ISSUE TITLE
No audio I/O backend is available

### ISSUE THREAD

**Issue by NitroNerd** [C0untFloyd/bark-gui#6]
When cloning voice, this error raising^
"  File "X:\LC\bark-gui\venv\lib\site-packages\torchaudio\backend\no_backend.py", line 16, in load                           
raise RuntimeError("No audio I/O backend is available.")                                                            
RuntimeError: No audio I/O backend is available.  "
How to fix it?

**Comment by C0untFloyd** [comment]
Windows? Did you do `pip install soundfile` ?
For Linux this would be `pip install sox`

If you're using Conda this might help too: `pip uninstall PySoundFile && pip install PySoundFile`

**Comment by seruko11** [comment]
@C0untFloyd I've had the same problem. I also get an error when I start up that says \bark-gui\venv\Lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
  
  I can find both: 
  soundfile          0.12.1
torchaudio         2.0.1

when I run pip list

**Comment by C0untFloyd** [comment]
Perhaps this is some kind of mismatch between Torch and the soundfile drivers.
Could you try if reinstalling both fixes it?

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 --force-reinstall
and
pip install soundfile --force-reinstall

**Comment by seruko11** [comment]
I was able to track this down, it was that soundfile didn't get added to
the venv, but was present

**Comment by C0untFloyd** [comment]
Nice, closing this then

**Comment by mixxs** [comment]
I had the same issue as you, which was resolved after I rebooted the pycharm IDE
