### ISSUE TITLE
After installation, the webui display does not open

### ISSUE THREAD

**Issue by NHLOCAL** [C0untFloyd/bark-gui#67]
After installing the package with the automatic installer for Windows, no software/webui interface opens as guaranteed.
In fact, although the system appears to have been installed successfully, there is no way to activate it.

Is it in a specific port, or did I just not understand something that is clear to everyone?!

I thank the respondent

**Comment by C0untFloyd** [comment]
The installer also runs it (in a browser).

**Comment by NHLOCAL** [comment]
> The installer also runs it (in a browser).

If so, it seems to be a bug. I know a batch code. In which line of code does the run in the browser take place?

**Comment by C0untFloyd** [comment]
Sorry but you are hard to understand and I don't know what's your problem.
[This](https://github.com/C0untFloyd/bark-gui/blob/main/webui.py#L456) starts the gradio server and launches the Browser Tab.
