### ISSUE TITLE
so-vits SVC models

### ISSUE THREAD

**Issue by kikoferrer** [C0untFloyd/bark-gui#80]
Can we use SVC trained models for bark?

**Comment by AIhasArrived** [comment]
Hello @SmoothBrainApe  , were you able to finish the installation? If yes, can you tell me what models were downloaded? I can't get them. Furthermore, would you upload them to some provider and send me link to download them please? My installation is stuck at this:
![image](https://github.com/C0untFloyd/bark-gui/assets/148225825/c5419467-5ce6-4851-863d-ad7b777cc558)
And it does not advance afterwards, nothing happens, I have been waiting for a hour or so..

**Comment by kikoferrer** [comment]
I uninstalled it ages ago. There are better tts out there if that's all you need.

**Comment by AIhasArrived** [comment]
Hello @SmoothBrainApe , sorry I had removed my comment, but I was wrong about something.
HOWEVER you caught my attention:) I have been doing this clone voice for 2 weeks now, if only you knew.. spent so much time on something called DL art school (relying on ozen to prepare voices etc), trained for hours and the models obtained were bad and the voices generated bad. Now I am trying Bark gui.
Do you mind SAVING ME and telling me what are the others better options out there ? :) (please).

**Comment by kikoferrer** [comment]
@AIhasArrived Do you have reddit? I can DM you there. I find it rude to the owner of this repo to suggest another repo so I will DM you there instead. DM me on Spirited_Employee_61. I will close this now with this comment as I am not using this anymore anyway.

**Comment by AIhasArrived** [comment]
Alright made an account and answered one of your comments, you should have received a notification on red  @SmoothBrainApe

**Comment by AIhasArrived** [comment]
Hey @SmoothBrainApe  sorry my reddit accoutn got suspended for some reason (I wrote a post on askmen and it got removed => account suspended, I could not send you more messages)
