### ISSUE TITLE
TypeError: Audio.__init__() got an unexpected keyword argument 'source' with windows_run.bat

### ISSUE THREAD

**Issue by chakaflus** [C0untFloyd/bark-gui#92]
When launching with windows_run.bat I got this error and crashes
 File "C:\Users\chak\Downloads\DSNSFW\bark-gui\installer\bark-gui\webui.py", line 366, in <module>
    swap_audio_filename = gr.Audio(label="Input audio.wav to swap voice", source="upload", type="filepath")
  File "C:\Users\chak\Downloads\DSNSFW\bark-gui\installer\installer_files\env\lib\site-packages\gradio\component_meta.py", line 152, in wrapper
    return fn(self, **kwargs)
TypeError: Audio.__init__() got an unexpected keyword argument 'source'

**Comment by lunar-studio** [comment]
What was the solution?

**Comment by vincurekf** [comment]
The solution for me was:
```
pip uninstall gradio
pip install gradio==3.50.2
```
Metioned here in another issue: https://github.com/C0untFloyd/bark-gui/issues/91#issuecomment-1879940572
